In [1]:
# import numpy as np
import numpy as np

In [2]:
#arithmetic operation on 1-d array

a=np.array([1,2,3.4])
b=np.array([3,6,4])

In [3]:
a

array([ 1. ,  2. ,  3.4])

In [4]:
b

array([3, 6, 4])

In [5]:
c=a+b
d=a-b
e=a*b
f=a/b
g=np.exp(a)

In [6]:
c

array([ 4. ,  8. ,  7.4])

In [7]:
d

array([-2. , -4. , -0.6])

In [8]:
e

array([  3. ,  12. ,  13.6])

In [9]:
f

array([ 0.33333333,  0.33333333,  0.85      ])

In [10]:
g

array([  2.71828183,   7.3890561 ,  29.96410005])

In [11]:
# comparison operators on arrays

a==b

array([False, False, False], dtype=bool)

In [12]:
a>b

array([False, False, False], dtype=bool)

In [13]:
a>1

array([False,  True,  True], dtype=bool)

In [14]:
np.array_equal(a,b)

False